services:
  - type: web
    name: signature-forgery-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
